### ISSUE TITLE
document mqtt events in wiki

### ISSUE THREAD

**Issue by PeterTheOne** [realraum/r3LoTHRPipeLEDs#1]
https://realraum.at/wiki/doku.php?id=roomauto:mqtt_topics

**Comment by btittelbach** [comment]
done.

available pattern names can be gotten from file names in the repository. Every "patt_<patternname>.lua" is a valid pattern that can be selected.

e.g. use <tt>./tools/mqtt_ctrl.py</tt> to control pipe via mqtt events:

```
./tools/mqtt_ctrl.py pattern circles
./tools/mqtt_ctrl.py pattern uspol
./tools/mqtt_ctrl.py pattern rainbow 5
./tools/mqtt_ctrl.py pattern movingspots 8
./tools/mqtt_ctrl.py pattern plasma
./tools/mqtt_ctrl.py restart
```
